# Generated by Django 2.2.16 on 2022-08-29 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20220828_1735'),
        ('titles', '0005_auto_20220829_1120'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Titles',
            new_name='Title',
        ),
    ]
